#!/bin/bash
antismash \
    --genefinding-tool prodigal \
    --taxon bacteria \
    genome.fna


    #The resulting GenBank files were subsequently parsed using the script: gbk_protocluster_parse_1.4.py
